### ISSUE TITLE
Miner exit takes ages and broken

### ISSUE THREAD

**Issue by sammy007** [str4d/zcash#10]
First ^C

```
Stopping miner
ZcashMinerThread terminated
```

nothing happens

2nd C^

```
^C[WARN] read_until: Bad file descriptor
Reconnecting in 3 seconds...
```

3rd ^C

```
^Cterminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  wait: Interrupted system call
Aborted
```

Finally I am free.

**Comment by str4d** [comment]
Yep, this is a known bug due to the use of synchronous Boost ASIO (which is a bit of a misnomer). I orignally switched to that version of @Genoil's Ethereum Stratum library as a basis for mine due to observed issues there with miner connectivity. Inability to stop the miner easily is annoying, but not a huge issue.

**Comment by daira** [comment]
Moved to https://github.com/zcash/zcash/issues/2378 ; should be closed here.
