### ISSUE TITLE
Standalone miner is blocked after sometime. 

### ISSUE THREAD

**Issue by sarath-hotspot** [str4d/zcash#12]
[logs.zip](https://github.com/str4d/zcash/files/538002/logs.zip)

Hi str4d, 
I ran standalone miner for ~20 minutes.  All threads in the miner blocked and it stopped generating hashes. 
I could not figure out the bug from stacktrace. 

Attached coredump & log file.

It was after integrating https://github.com/str4d/zcash/pull/11

**Comment by JanKalin** [comment]
I can confirm that there are problems. I have two machines:
- `Ubuntu 16.04.1 LTS` in a VM with `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609` and
- `Debian GNU/Linux 7.11 (wheezy)` natively with  `gcc (Debian 4.7.2-5) 4.7.2`

Because the Debian's GCC is older, I need to make some edits to get Zcash to compile. However:
- These edits are nowhere near the solver code - see [mydiff.txt](https://github.com/str4d/zcash/files/541473/mydiff.txt)
- I need to make the same edits for both the Zcash official release and str4d's fork for the standalone miner
- Both the Zcash and and the fork work perfectly on both machines, all the tests pass, the zcashd from the official release mines, as does zcash-miner.

But the `zcash-miner` with Tromp's solver works only on the Ubuntu machine - well, it has now been running for around 40 minutes and is still mining. If I run it without arguments, it starts running test solves on Ubuntu, while on Debian it just hangs. If I connect to a stratum server (zec.suprnova.cc or zmine.io) from Debian it segfaults.

Note that Tromp's solver from https://github.com/tromp/equihash works fine on both machines.

EDIT: Moved this from the pull request comments

**Comment by jinsu1701** [comment]
I seem to face similar problems. I usually then stop the miner and restart to get it working again. 
As far as I can see, I did not observe these problems on the RC1 version. 
I am using 1 core only for execution and memory usage is also not very high.
My miner is using the Zmine pool, 

The situation presents itself as follows:
The miner is running for some time (the last attempt was 77 minutes), then the following entry appears in the log:
`ZcashMinerThread runtime error: write: Broken pipe`

After this, there is no further processing as the CPU load drops to minimal levels.

Following this event, the miner seems to have lost the pool connection and tries to reconnect:
```
Connecting to stratum server zmine.io:1337
Connected!
```

Then this warning is logged and the connection seems to be lost again:
```
[WARN] read_until: End of file
Reconnecting in 3 seconds...
```

This situation repeats for several times, sometimes this log entry appears also:
`[WARN] read_until: Connection reset by peer`

After some time of retrying to connect, the miner seems to have a stable connection again, a target is logged and the worker is authorised, But the miner does only log the reception of new jobs but does no processing anymore.

**Comment by JanKalin** [comment]
At least for the `Debian GNU/Linux 7.11 (wheezy)` natively with `gcc (Debian 4.7.2-5) 4.7.2` the problem is most likely some issue with the compiler, templates and bad C++11 support.

I had the same issue with https://github.com/nicehash/nheqminer - it would run benchmarks just fine, but when connecting to a stratum server it segfaulted. I ran it with debugger and it failed in the function
```
template <typename Miner, typename Job, typename Solution>
void StratumClient<Miner, Job, Solution>::workLoop()
```
of the `src/libstratum/StratumClient.cpp`.

Apparently the object is not properly constructed and the very first line `while (m_running)` references a null pointer and crashes the program.

**Comment by str4d** [comment]
Thanks for the feedback! I'll put some time into improvements after I get some sleep :sweat_smile:

**Comment by daira** [comment]
Moved to https://github.com/zcash/zcash/issues/2379 ; can be closed here.
