### ISSUE TITLE
How install Standalone Test CPU Miner Sourcecode (thx str4d!)

### ISSUE THREAD

**Issue by tor888** [str4d/zcash#9]
Hello here.Said me please 
How install Standalone Test CPU Miner Sourcecode (thx str4d!) on Ubuntu 16.04.
Which dependies and commands?
Thanx.

**Comment by l0c0luke** [comment]
http://zmine.io/

**Comment by str4d** [comment]
Follow the same steps to build as the [Zcash Beta Guide](https://github.com/zcash/zcash/wiki/Beta-Guide), with the following changes:

- Instead of `git clone https://github.com/zcash/zcash.git`, use `git clone https://github.com/str4d/zcash.git` (obviously :smile: )
- Instead of `git checkout v1.0.0-rc1` use `git checkout standalone-miner`

Once built, run `./src/zcash-miner -?` to see the available configuration options.
